instrumentation:
  root: ./src
  extensions:
    - .js
  excludes: ["node_modules", "build", "**/*.spec.js", "**/*.scenario.js"]
  include-all-sources: true
reporting:
  dir: ./coverage
  reports:
    - lcov
    - text
